import type { TopicGroup } from "@/types";

export const topicGroups: TopicGroup[] = [
  // ── Physiology ──
  {
    id: "sub-physiology-coagulation",
    moduleId: "sub-physiology",
    name: "Coagulation Cascade",
    topics: [
      "Coagulation Cascade",
      "Coagulation Cascade - Extrinsic Pathway",
      "Coagulation Cascade - Intrinsic Pathway",
      "Coagulation Cascade - Common Pathway",
      "Thrombin - Actions",
      "Fibrin Clot Formation",
      "Clot Retraction",
      "Fate of a Thrombus",
      "Fibrinolysis",
      "Positive Feedback in Coagulation",
      "Coagulation Factors",
      "Vitamin K and Coagulation",
      "Coagulation Disorders - Hemophilia",
      "Coagulation Disorders - Hemophilia B",
      "Von Willebrand Disease",
      "Coagulation",
    ],
  },
  {
    id: "sub-physiology-wbc",
    moduleId: "sub-physiology",
    name: "WBCs & Granulocytes",
    topics: [
      "Leukocytes - Overview",
      "WBC Differential Count",
      "Neutrophils - Structure",
      "Neutrophil Migration - Diapedesis",
      "Neutrophil Killing Mechanisms",
      "NETosis",
      "Neutrophilia",
      "Basophils - Structure",
      "Basophils - Allergic Reaction",
      "Eosinophils - Structure",
      "Eosinophils - Anti-Parasitic Function",
      "Eosinophils - Moderating Allergic Reactions",
      "Eosinophilia",
      "Lymphocytes",
    ],
  },
  {
    id: "sub-physiology-blood",
    moduleId: "sub-physiology",
    name: "Blood & Erythropoiesis",
    topics: [
      "Blood Composition",
      "Plasma vs Serum",
      "Plasma Proteins",
      "RBC Structure",
      "Haematocrit and RBC Indices",
      "Haematopoiesis",
      "Haematopoiesis - Fetal",
      "Erythropoietin (EPO)",
      "EPO in Renal Failure",
      "Nutritional Factors - Vitamin B12 and Folate",
      "Polycythaemia",
    ],
  },
  {
    id: "sub-physiology-general",
    moduleId: "sub-physiology",
    name: "General Physiology",
    topics: ["General Physiology"],
  },
  {
    id: "sub-physiology-homeostasis",
    moduleId: "sub-physiology",
    name: "Homeostasis",
    topics: ["Homeostasis"],
  },
  {
    id: "sub-physiology-feedback",
    moduleId: "sub-physiology",
    name: "Feedback Mechanisms",
    topics: ["Feedback Mechanisms"],
  },
  {
    id: "sub-physiology-organ-systems",
    moduleId: "sub-physiology",
    name: "Organ Systems in Homeostasis",
    topics: ["Organ Systems in Homeostasis"],
  },
  {
    id: "sub-physiology-cell",
    moduleId: "sub-physiology",
    name: "Cell Physiology",
    topics: ["Cell Physiology"],
  },
  {
    id: "sub-physiology-erythropoiesis",
    moduleId: "sub-physiology",
    name: "Erythropoiesis & EPO",
    topics: ["Erythropoiesis & EPO"],
  },
  {
    id: "sub-physiology-rbc",
    moduleId: "sub-physiology",
    name: "RBC Indices & Anemia",
    topics: ["RBC Indices & Anemia"],
  },
  {
    id: "sub-physiology-immunity",
    moduleId: "sub-physiology",
    name: "WBC & Immunity",
    topics: ["WBC & Immunity"],
  },

  // ── Anatomy ──
  {
    id: "sub-anatomy-gametogenesis",
    moduleId: "sub-anatomy",
    name: "Gametogenesis & Chromosomal Aberrations",
    topics: ["Embryology - Gametogenesis & Chromosomal Aberrations"],
  },
  {
    id: "sub-anatomy-spermatogenesis",
    moduleId: "sub-anatomy",
    name: "Spermatogenesis & Oogenesis",
    topics: ["Embryology - Spermatogenesis & Oogenesis"],
  },
  {
    id: "sub-anatomy-fertilization",
    moduleId: "sub-anatomy",
    name: "Fertilization & Implantation",
    topics: ["Embryology - Fertilization & Implantation"],
  },
  {
    id: "sub-anatomy-placentation",
    moduleId: "sub-anatomy",
    name: "Second Week & Placentation",
    topics: ["Embryology - Second Week & Placentation"],
  },
  {
    id: "sub-anatomy-cord",
    moduleId: "sub-anatomy",
    name: "Umbilical Cord, Allantois & Yolk Sac",
    topics: ["Embryology - Umbilical Cord, Allantois, Yolk Sac"],
  },
  {
    id: "sub-anatomy-hematopoiesis",
    moduleId: "sub-anatomy",
    name: "Thymus, Spleen & Hematopoiesis",
    topics: ["Embryology - Thymus, Spleen, Hematopoiesis"],
  },
  {
    id: "sub-anatomy-clinical-embryo",
    moduleId: "sub-anatomy",
    name: "Clinical Embryology",
    topics: ["Embryology - Clinical Embryology"],
  },
  {
    id: "sub-anatomy-spleen",
    moduleId: "sub-anatomy",
    name: "Spleen",
    topics: ["Gross Anatomy - Spleen"],
  },
  {
    id: "sub-anatomy-tonsils",
    moduleId: "sub-anatomy",
    name: "Palatine Tonsils & Waldeyer's Ring",
    topics: ["Gross Anatomy - Palatine Tonsils & Waldeyer's Ring"],
  },
  {
    id: "sub-anatomy-general",
    moduleId: "sub-anatomy",
    name: "General Anatomy",
    topics: ["General Anatomy - Terms, Bones, Joints, Muscles"],
  },
  {
    id: "sub-anatomy-histology-epithelium",
    moduleId: "sub-anatomy",
    name: "Histology — Basic Tissues & Epithelium",
    topics: ["Histology - Basic Tissues & Epithelium"],
  },
  {
    id: "sub-anatomy-histology-junctions",
    moduleId: "sub-anatomy",
    name: "Histology — Cell Junctions & Glands",
    topics: ["Histology - Cell Junctions & Glands"],
  },
  {
    id: "sub-anatomy-histology-lymphoid",
    moduleId: "sub-anatomy",
    name: "Histology — Lymphoid Organs",
    topics: ["Histology - Lymphoid Organs"],
  },

  // ── Biochemistry ──
  {
    id: "sub-biochemistry-jaundice",
    moduleId: "sub-biochemistry",
    name: "Jaundice & Bilirubin Metabolism",
    topics: ["Jaundice & Bilirubin Metabolism"],
  },
  {
    id: "sub-biochemistry-vitamink",
    moduleId: "sub-biochemistry",
    name: "Vitamin K",
    topics: ["Vitamin K"],
  },
  {
    id: "sub-biochemistry-iron",
    moduleId: "sub-biochemistry",
    name: "Iron Metabolism",
    topics: ["Iron Metabolism"],
  },
  {
    id: "sub-biochemistry-hb",
    moduleId: "sub-biochemistry",
    name: "Hemoglobin Structure & Function",
    topics: ["Hemoglobin Structure & Function"],
  },
  {
    id: "sub-biochemistry-b12folate",
    moduleId: "sub-biochemistry",
    name: "Hematopoietic Vitamins (B12 & Folate)",
    topics: ["Hematopoietic Vitamins (B12 & Folate)"],
  },
  {
    id: "sub-biochemistry-heme-disorders",
    moduleId: "sub-biochemistry",
    name: "Inherited Disorders of Heme",
    topics: ["Inherited Disorders of Heme"],
  },
  {
    id: "sub-biochemistry-porphyria",
    moduleId: "sub-biochemistry",
    name: "Heme Synthesis & Porphyrias",
    topics: ["Heme Synthesis & Porphyrias"],
  },
  {
    id: "sub-biochemistry-membranes",
    moduleId: "sub-biochemistry",
    name: "Cell Membranes & Organelles",
    topics: ["Cell Membranes & Organelles"],
  },
  {
    id: "sub-biochemistry-enzymes-markers",
    moduleId: "sub-biochemistry",
    name: "Marker Enzymes",
    topics: ["Marker Enzymes"],
  },
  {
    id: "sub-biochemistry-nucleicacids",
    moduleId: "sub-biochemistry",
    name: "Chemistry of Nucleic Acids",
    topics: ["Chemistry of Nucleic Acids"],
  },
  {
    id: "sub-biochemistry-dnarna",
    moduleId: "sub-biochemistry",
    name: "DNA and RNA",
    topics: ["DNA and RNA"],
  },
  {
    id: "sub-biochemistry-carbs",
    moduleId: "sub-biochemistry",
    name: "Carbohydrate Chemistry",
    topics: ["Carbohydrate Chemistry"],
  },
  {
    id: "sub-biochemistry-enzymes",
    moduleId: "sub-biochemistry",
    name: "Enzymes",
    topics: ["Enzymes"],
  },

  // ── Minor Subjects ──
  {
    id: "sub-minor-bps",
    moduleId: "sub-minor",
    name: "BPS Model & Integrated Health",
    topics: ["BPS Model & Integrated Health"],
  },
  {
    id: "sub-minor-pif",
    moduleId: "sub-minor",
    name: "Professional Identity Formation",
    topics: ["Professional Identity Formation"],
  },
  {
    id: "sub-minor-professionalism",
    moduleId: "sub-minor",
    name: "Professionalism",
    topics: ["Professionalism"],
  },
  {
    id: "sub-minor-neurochemistry",
    moduleId: "sub-minor",
    name: "Neurochemistry of Behavior",
    topics: ["Neurochemistry of Behavior"],
  },
  {
    id: "sub-minor-enzymes-markers",
    moduleId: "sub-minor",
    name: "Enzymes as Diagnostic Markers",
    topics: ["Enzymes as Diagnostic Markers"],
  },
  {
    id: "sub-minor-ultrasound",
    moduleId: "sub-minor",
    name: "Ultrasound in Fetal Examination",
    topics: ["Ultrasound in Fetal Examination"],
  },
  {
    id: "sub-minor-teratogenesis",
    moduleId: "sub-minor",
    name: "Teratogenesis",
    topics: ["Teratogenesis"],
  },
  {
    id: "sub-minor-hypersensitivity",
    moduleId: "sub-minor",
    name: "Hypersensitivity",
    topics: ["Hypersensitivity"],
  },
  {
    id: "sub-minor-hemoglobinopathy",
    moduleId: "sub-minor",
    name: "Haemoglobinopathies",
    topics: ["Haemoglobinopathies"],
  },
  {
    id: "sub-minor-bloodborne",
    moduleId: "sub-minor",
    name: "Blood-Borne Diseases & Transfusion",
    topics: ["Blood-Borne Diseases & Transfusion"],
  },
  {
    id: "sub-minor-anemia",
    moduleId: "sub-minor",
    name: "Anemia",
    topics: ["Anemia"],
  },
  {
    id: "sub-minor-pharmacokinetics",
    moduleId: "sub-minor",
    name: "Pharmacokinetics & Pharmacodynamics",
    topics: ["Pharmacokinetics & Pharmacodynamics"],
  },
  {
    id: "sub-minor-parasitology",
    moduleId: "sub-minor",
    name: "Parasitology & Bacteriology",
    topics: ["Parasitology & Bacteriology"],
  },
];

export function getTopicGroupsByModuleId(moduleId: string): TopicGroup[] {
  return topicGroups.filter((tg) => tg.moduleId === moduleId);
}
